// vueJS/src/components/language.vue
<template>
    <div>
        <form @change="checkForm">
            <p>Selecteer een taal dat u beheerst</p>  
            <select v-model="selectedTaal.taal">
                <option v-for="taal in talen" v-bind:key="taal" v-bind:value="taal">
                    {{taal}}
                </option>
            </select>
            <p>Selecteer hoe goed u deze beheerst</p>
            <select v-model="selectedTaal.beheersing">
                <option>1</option>
                <option>2</option>
                <option>3</option>
            </select>
            <br>
            <input type="button" value="Toevoegen" v-on:click="add" v-bind:disabled="disabled">
            <br> <br>
            <input type="button" value="Opslaan" @click="save">
        </form>

    </div>
</template>
<script>
    import axios from 'axios';
    import Profile from '@/components/profile'

    export default {
        
        data(){
            return {
                user: this.$parent.user,
                talen: ["Nederlands", "Engels", "Duits", "Frans", "Fins", "Spaans", "Italiaans", "Portugees"],
                selectedTaal: [],
                disabled: true,
                lijst : new Array()
            }
        },
        methods: {
            checkForm: function() {

                if(this.selectedTaal.taal != null && this.selectedTaal.beheersing != null){
                    this.disabled = false;
                }

            },
            add: function (){
      
                this.user.languages.push(this.selectedTaal);
            
                this.user.languages.forEach(lan => {

                    this.lijst.push(
                        {
                            "taal": lan.taal,
                            "beheersing" : lan.beheersing
                        }
                    );
                    
                });

            },
            save: function (){

                console.log(this.lijst)

                 axios
                    .patch('http://localhost:3000/users/1',{
                        languages: lijst
                    })
                    .then(response => {
                        console.log(response);
                    })
                    .catch(e => {
                        console.log(e);
                    });

                this.$parent.languageComp = true;
                this.$parent.langcurrentComp = null;
            }
        }
    }
</script>

// angular/src/app/language/language.component.ts
import { Component, OnInit, EventEmitter, Input, NgModule, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { User } from '../user';
import { UserService } from '../user.service';

@Component({
  selector: 'app-language',
  templateUrl: './language.component.html',
  styleUrls: ['./language.component.css']
})

@NgModule({
  imports: [
    CommonModule
  ]
})

export class LanguageComponent implements OnInit {

  @Input() language: boolean;
  @Input() user: User;
  @Output() onLangEdited = new EventEmitter<boolean>();
  
  langList = [
    "Nederlands", "Engels", "Duits", "Frans", "Duits", "Spaans", "Italiaans", "Chinees", "Japans", "Noors", "Fins"
  ];
  selectedValue: string;
  selectedControl: number;

  constructor(private userService: UserService) { }

  ngOnInit() {
  }

  add(): void {

    let selectedLanguage = { "language": this.selectedValue, "control": this.selectedControl };
    this.user.languages.push(selectedLanguage);
    this.userService.updateUser(this.user).subscribe(() => {
      console.log("UPDATED")
    })
  }

  save(): void {

    this.language = true;

    this.onLangEdited.emit(true);

  }

  delete(taal: Object): void {
    if (this.user.languages.length > 0) {
      this.user.languages = this.user.languages.filter(obj => obj !== taal);
    }
  }

}

<div *ngIf="language == false">


  <div *ngIf="user.languages.length > 0">
      <div *ngFor="let taal of user.languages" class="taal">
        {{taal.language}}
        <a (click)="delete(taal)">Verwijderen</a>
      </div>
    </div>
  <div *ngIf="user.languages.length == 0">
      Voeg hier een taal toe en selecteer hoe goed u het beheerst.
    
    </div>

  <form name="languageForm" #langForm="ngForm">
      <br>
    <label for="taal">Voeg een taal toe</label>

    <select required name="taal" id="taal" [(ngModel)]="selectedValue">
      <option *ngFor="let language of langList" value="{{language}}" >{{language}}</option>
    </select>

    <br>

    <label for="beheersing">Beheersing van deze taal</label>
    <select required name="beheersing" id="beheersing" [(ngModel)]="selectedControl">
      <option value="0" selected>Matig</option>
      <option value="1">Goed</option>
      <option value="2">Uitstekend</option>
    </select>

    <button [disabled]="langForm.invalid" type="button" (click)="add()">Toevoegen</button>

  </form>

  <button (click)="save()">
    Opslaan
  </button>
</div>
