// angular/src/app/personalia/personalia.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';
import { User } from '../user';
import { UserService } from '../user.service';


@Component({
  selector: 'app-personalia',
  templateUrl: './personalia.component.html',
  styleUrls: ['./personalia.component.css']
})



export class PersonaliaComponent implements OnInit {
  @Input() personalia: boolean;
  @Input() user: User;

  @Output() onEdited = new EventEmitter<boolean>();

  

  constructor(private userService: UserService) { }

  ngOnInit() {
  }

  save() : void {

    console.log("Terug naar de parent");

    this.userService.updateUser(this.user).subscribe(user => this.user = user);

    this.personalia = true;

    this.onEdited.emit(true);

  }

}

<div *ngIf="personalia == false">
  <form name="userForm" #userForm="ngForm">
    <label for="firstname">Voornaam: </label>
    <input name="firstname" id="firstname" class="form-control" minlength="3" [(ngModel)]="user.firstname">

    <label for="lastname">Achternaam: </label>
    <input name="lastname" id="lastname" class="form-control" minlength="3" [(ngModel)]="user.lastname">

    <label for="age">Leeftijd: </label>
    <input type="number" name="age" id="age" class="form-control" [(ngModel)]="user.age">

    <label for="address">Adres: </label>
    <input name="address" id="address" class="form-control" [(ngModel)]="user.address">

    <label for="sex">Geslacht: </label>
    <label for="m">Man </label>
    <input type="radio" name="sex" id="m" value="man" [(ngModel)]="user.sex">
    <label for="v">Vrouw </label>
    <input type="radio" name="sex" id="v" value="vrouw" [(ngModel)]="user.sex">

    <label for="email">Emailadres: </label>
    <input type="email" name="email" id="email" required class="form-control" email [(ngModel)]="user.email" #email="ngModel">

    <span *ngIf="email.invalid && email.dirty" class="red">Email is niet valid</span>

    <button [disabled]="userForm.form.invalid && email.dirty" (click)="save()"> Save </button>
  </form>
</div>

// vueJS/src/components/personalia.vue
<template>
    <div class="gegevens">
        <div>
            <label for="firstname">Voornaam: </label>
            <label for="lastname">Achternaam: </label>
            <label for="age">Leeftijd: </label>
            <label for="address">Adres: </label>
            <label for="sex">Geslacht: </label>
            <label for="mail">Emailadres: </label>
        </div>
        <form @change="checkForm">
            <p v-if="errors.length">
                <ul>
                    <li v-for="error in errors" v-bind:key="error.id">{{ error }}</li>
                </ul>
            </p>
            <p>    
                <input type="text" name="firstname" id="firstname" v-model="user.firstname">
            </p>
            <p>
                <input type="text" name="lastname" id="lastname" v-model="user.lastname">
            </p>
            <p>  
                <input type="number" name="age" id="age" v-model="user.age">
            </p>
            <p>
                <input type="text" name="address" id="address" v-model="user.address">
            </p>
            <p>      
                <label for="m">Man: </label>
                <input type="radio" value="Man" id="m" name="sex" v-model="user.sex">
                <label for="v">Vrouw: </label>
                <input type="radio" value="Vrouw" id="v" name="sex" v-model="user.sex">
            </p>
            <p>  
                <input type="text" name="mail" id="mail" v-model="user.email">
            </p>
            <input type="button" value="SUBMIT" v-on:click="submit">
        </form>
    </div>
</template>

<script>
    import axios from 'axios';
    import Profile from '@/components/profile'
    
    
    export default {
        props: {
            usero: {
                type: Object,
                required: false
            }
        },
        data() {
            return {
                errors: [],
                user: this.$parent.user
            }
        },
        methods: {
    
            submit: function() {
    
                axios
                    .patch('http://localhost:3000/users/1', {
                        firstname: this.user.firstname,
                        lastname: this.user.lastname,
                        age: this.user.age,
                        address: this.user.address,
                        sex: this.user.sex,
                        email: this.user.email
                    })
                    .then(response => {
                        console.log(response);
                    })
                    .catch(e => {
    
                        console.log(errors);
                    })

                this.$parent.personaliaComp = true;
                this.$parent.perscurrentcomp = null;

    
    
            },
            checkForm: function() {
                // telkens er iets veranderd van input in de form, kom je in deze functie terecht
                if(this.user.email != null && this.user.email != ""){
                    console.log("email is ingevuld");

                    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
                    if(!re.test(this.user.email)){
                        this.errors.push(" Vul een geldig emailadres in");
                    }
                }
                else{
                    this.errors =[];
                }
            }
    
        },
        beforeMount() {
            console.log(this.$parent.user);
            
        }
    
    }
</script>
<style src="../css/personalia.css">
</style>
